# Generated by Django 5.0.2 on 2024-07-05 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_agegender_created_at_agegender_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LprAlpha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plate_number', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lpralpha', to='dashboard.camera')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
