# Generated by Django 5.0.2 on 2024-07-20 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_lpralpha'),
    ]

    operations = [
        migrations.AddField(
            model_name='lpralpha',
            name='confidence_score',
            field=models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
            preserve_default=False,
        ),
    ]
