# Generated by Django 5.0.2 on 2024-07-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_lpralpha_confidence_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lpralpha',
            name='plate_number',
            field=models.CharField(max_length=20),
        ),
    ]
