# Generated by Django 5.0.2 on 2024-07-22 16:42

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_lpralpha_plate_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lpralpha',
            name='image',
        ),
        migrations.AddField(
            model_name='lpralpha',
            name='car_image',
            field=models.ImageField(default='path/to/placeholder.jpg', upload_to=dashboard.models.car_image_upload_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lpralpha',
            name='lpr_image',
            field=models.ImageField(default='path/to/placeholder.jpg', upload_to=dashboard.models.license_plate_image_upload_path),
            preserve_default=False,
        ),
    ]
